version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: monologue
      MYSQL_USER: monologue
      MYSQL_PASSWORD: monologue
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    ports:
      - "33306:3306"
    volumes:
      - ./data:/var/lib/mysql:delegated
